### ISSUE TITLE
Wolfenstein 2 VR

### ISSUE THREAD

**Issue by tkapis** [helifax/Vk3DVision-Public#2]
Game no longer works with SteamVR 2.1 probably due to the changed desktop theater. 

A completely wrong resolution  is displayed in the info window and the game just hangs when  loading a save.

**Comment by helifax** [comment]
Hmm..  there is no issue that I can see with SteamVR 2.1 and Wolfenstein 2 VR:
![SteamVr 2 1](https://github.com/helifax/Vk3DVision-Public/assets/3100082/bc8e4ec1-6f0a-45dd-b3bc-14e619f55d96)

**Comment by helifax** [comment]
Oh.. I think I understand what you are saying... I was able to see this one time.
But, I just restarted the game it worked fine.
It sounds that sometimes the runtime is not being initialised correctly from what I can tell.

**Comment by tkapis** [comment]
Hi, if you check the performance I think that you will find that it is terrible. This is because the desktop theater screen is being displayed behind the game screen and you don't seem to be able to prevent it with the new SteamVR UI.

I have now solved it for the moment by loading the temp_1.2.5 from the betas of SteamVR AND moving the steamvr_desktop_game_theater.exe from the SteamVR Tools.

If you view the discussions of SteamVR you will see that a lot of people are having serious problems with SteamVR 2.1.

Actually I don't think that there is much you can do to solve it so we'll just wait for Valve to fix this.

BTW Could you please update your check on the video card as I have a RTX 4080 and have to confirm the pop up every time when starting the game.

**Comment by helifax** [comment]
Strange. I just played the game around 40 minutes. And I do not have this issues. I do not see any issue with the SteamVR game theater screen. It just loads into VR mode as any VR game.
I have SteamVR Game Theater Mode disabled in Steam from before the SteamVR 2.0 update. I now see the option is missing from Steam?!

The VR mode is also coded as a native VR application, so I am not sure why the VR Game Theater appears, unless like you said it's a bug in SteamVR.

I am also running a RTX 4090 and I updated that check last year, it I remember right. What version of Vk3dVision are you using? Are you running 4.22.16?
https://github.com/helifax/Vk3DVision-Public/releases/tag/v.4.22.16

**Comment by helifax** [comment]
Ok. I see.. You are starting Wolf 2 through VR environment right? If you start it from the Desktop the VR screen thingy is not enabled and the game starts directly into VR.
For this you need to either see the desktop in VR and start the game from Steam, or get your headset off go to your PC and start the game from Steam.
Very strange how Steam made it work now.

**Comment by tkapis** [comment]
I start the game from a desktop shortcut generated from steam, anyway my solution works for the moment.

I was using the Vk3DVision from the download of the mod for the game, didn't think to check if there was an update duh. Thanks for the info.

**Comment by helifax** [comment]
Issue seems to be fixed. Happy to reopen if required :)
